background="#24273a"   #------------------------- Catppuccin Macchiato Base
text="#cad3f5"   #------------------------------- Catppuccin Macchiato Text
subtle="#a5adcb"   #----------------------------- Catppuccin Macchiato Subtext0
warning-text="#ed8796"   #----------------------- Catppuccin Macchiato Red
text-special-one="#f4dbd6"   #------------------- Catppuccin Macchiato Rosewater
text-special-two="#a6da95"   #------------------- Catppuccin Macchiato Green
top-bar-background="#a5adcb"   #----------------- Catppuccin Macchiato Subtext0
top-bar-text="#24273a"   #----------------------- Catppuccin Macchiato Base
status-bar-background="#a5adcb"   #-------------- Catppuccin Macchiato Subtext0
status-bar-text="#24273a"   #-------------------- Catppuccin Macchiato Base
status-bar-view-background="#f4dbd6"   #--------- Catppuccin Macchiato Rosewater
status-bar-view-text="#24273a"   #--------------- Catppuccin Macchiato Base
command-text="#cad3f5"   #----------------------- Catppuccin Macchiato Text
list-selected-background="#f4dbd6"   #----------- Catppuccin Macchiato Rosewater
list-selected-text="#24273a"   #----------------- Catppuccin Macchiato Base
list-selected-inactive-background="#494d64"   #-- Catppuccin Macchiato Surface1
list-selected-inactive-text="#a5adcb"   #-------- Catppuccin Macchiato Subtext0
controls-text="#cad3f5"   #---------------------- Catppuccin Macchiato Text
controls-highlight="#a6da95"   #----------------- Catppuccin Macchiato Green
autocomplete-background="#24273a"   #------------ Catppuccin Macchiato Base
autocomplete-text="#cad3f5"   #------------------ Catppuccin Macchiato Text
autocomplete-selected-background="#f4dbd6"   #--- Catppuccin Macchiato Rosewater
autocomplete-selected-text="#24273a"   #--------- Catppuccin Macchiato Base
button-color-one="#ed8796"   #------------------- Catppuccin Macchiato Red
button-color-two="#24273a"   #------------------- Catppuccin Macchiato Base
timeline-name-background="#24273a"   #----------- Catppuccin Macchiato Base
timeline-name-text="#f4dbd6"   #----------------- Catppuccin Macchiato Rosewater
