background="#1e1e2e"   #------------------------- Catppuccin Mocha Base
text="#cdd6f4"   #------------------------------- Catppuccin Mocha Text
subtle="#a6adc8"   #----------------------------- Catppuccin Mocha Subtext0
warning-text="#f38ba8"   #----------------------- Catppuccin Mocha Red
text-special-one="#cba6f7"   #------------------- Catppuccin Mocha Mauve
text-special-two="#a6e3a1"   #------------------- Catppuccin Mocha Green
top-bar-background="#a6adc8"   #----------------- Catppuccin Mocha Subtext0
top-bar-text="#1e1e2e"   #----------------------- Catppuccin Mocha Base
status-bar-background="#a6adc8"   #-------------- Catppuccin Mocha Subtext0
status-bar-text="#1e1e2e"   #-------------------- Catppuccin Mocha Base
status-bar-view-background="#cba6f7"   #--------- Catppuccin Mocha Mauve
status-bar-view-text="#1e1e2e"   #--------------- Catppuccin Mocha Base
command-text="#cdd6f4"   #----------------------- Catppuccin Mocha Text
list-selected-background="#cba6f7"   #----------- Catppuccin Mocha Mauve
list-selected-text="#1e1e2e"   #----------------- Catppuccin Mocha Base
list-selected-inactive-background="#45475a"   #-- Catppuccin Mocha Surface1
list-selected-inactive-text="#a6adc8"   #-------- Catppuccin Mocha Subtext0
controls-text="#cdd6f4"   #---------------------- Catppuccin Mocha Text
controls-highlight="#a6e3a1"   #----------------- Catppuccin Mocha Green
autocomplete-background="#1e1e2e"   #------------ Catppuccin Mocha Base
autocomplete-text="#cdd6f4"   #------------------ Catppuccin Mocha Text
autocomplete-selected-background="#cba6f7"   #--- Catppuccin Mocha Mauve
autocomplete-selected-text="#1e1e2e"   #--------- Catppuccin Mocha Base
button-color-one="#f38ba8"   #------------------- Catppuccin Mocha Red
button-color-two="#1e1e2e"   #------------------- Catppuccin Mocha Base
timeline-name-background="#1e1e2e"   #----------- Catppuccin Mocha Base
timeline-name-text="#cba6f7"   #----------------- Catppuccin Mocha Mauve
