background="#eff1f5"   #------------------------- Catppuccin Latte Base
text="#4c4f69"   #------------------------------- Catppuccin Latte Text
subtle="#6c6f85"   #----------------------------- Catppuccin Latte Subtext0
warning-text="#d20f39"   #----------------------- Catppuccin Latte Red
text-special-one="#fe640b"   #------------------- Catppuccin Latte Peach
text-special-two="#40a02b"   #------------------- Catppuccin Latte Green
top-bar-background="#6c6f85"   #----------------- Catppuccin Latte Subtext0
top-bar-text="#eff1f5"   #----------------------- Catppuccin Latte Base
status-bar-background="#6c6f85"   #-------------- Catppuccin Latte Subtext0
status-bar-text="#eff1f5"   #-------------------- Catppuccin Latte Base
status-bar-view-background="#fe640b"   #--------- Catppuccin Latte Peach
status-bar-view-text="#eff1f5"   #--------------- Catppuccin Latte Base
command-text="#4c4f69"   #----------------------- Catppuccin Latte Text
list-selected-background="#fe640b"   #----------- Catppuccin Latte Peach
list-selected-text="#eff1f5"   #----------------- Catppuccin Latte Base
list-selected-inactive-background="#bcc0cc"   #-- Catppuccin Latte Surface1
list-selected-inactive-text="#6c6f85"   #-------- Catppuccin Latte Subtext0
controls-text="#4c4f69"   #---------------------- Catppuccin Latte Text
controls-highlight="#40a02b"   #----------------- Catppuccin Latte Green
autocomplete-background="#eff1f5"   #------------ Catppuccin Latte Base
autocomplete-text="#4c4f69"   #------------------ Catppuccin Latte Text
autocomplete-selected-background="#fe640b"   #--- Catppuccin Latte Peach
autocomplete-selected-text="#eff1f5"   #--------- Catppuccin Latte Base
button-color-one="#d20f39"   #------------------- Catppuccin Latte Red
button-color-two="#eff1f5"   #------------------- Catppuccin Latte Base
timeline-name-background="#eff1f5"   #----------- Catppuccin Latte Base
timeline-name-text="#fe640b"   #----------------- Catppuccin Latte Peach
