background="#1e1e2e"   #------------------------- Catppuccin Mocha Base
text="#cdd6f4"   #------------------------------- Catppuccin Mocha Text
subtle="#a6adc8"   #----------------------------- Catppuccin Mocha Subtext0
warning-text="#f38ba8"   #----------------------- Catppuccin Mocha Red
text-special-one="#eba0ac"   #------------------- Catppuccin Mocha Maroon
text-special-two="#a6e3a1"   #------------------- Catppuccin Mocha Green
top-bar-background="#a6adc8"   #----------------- Catppuccin Mocha Subtext0
top-bar-text="#1e1e2e"   #----------------------- Catppuccin Mocha Base
status-bar-background="#a6adc8"   #-------------- Catppuccin Mocha Subtext0
status-bar-text="#1e1e2e"   #-------------------- Catppuccin Mocha Base
status-bar-view-background="#eba0ac"   #--------- Catppuccin Mocha Maroon
status-bar-view-text="#1e1e2e"   #--------------- Catppuccin Mocha Base
command-text="#cdd6f4"   #----------------------- Catppuccin Mocha Text
list-selected-background="#eba0ac"   #----------- Catppuccin Mocha Maroon
list-selected-text="#1e1e2e"   #----------------- Catppuccin Mocha Base
list-selected-inactive-background="#45475a"   #-- Catppuccin Mocha Surface1
list-selected-inactive-text="#a6adc8"   #-------- Catppuccin Mocha Subtext0
controls-text="#cdd6f4"   #---------------------- Catppuccin Mocha Text
controls-highlight="#a6e3a1"   #----------------- Catppuccin Mocha Green
autocomplete-background="#1e1e2e"   #------------ Catppuccin Mocha Base
autocomplete-text="#cdd6f4"   #------------------ Catppuccin Mocha Text
autocomplete-selected-background="#eba0ac"   #--- Catppuccin Mocha Maroon
autocomplete-selected-text="#1e1e2e"   #--------- Catppuccin Mocha Base
button-color-one="#f38ba8"   #------------------- Catppuccin Mocha Red
button-color-two="#1e1e2e"   #------------------- Catppuccin Mocha Base
timeline-name-background="#1e1e2e"   #----------- Catppuccin Mocha Base
timeline-name-text="#eba0ac"   #----------------- Catppuccin Mocha Maroon
