background="#303446"   #------------------------- Catppuccin Frappé Base
text="#c6d0f5"   #------------------------------- Catppuccin Frappé Text
subtle="#a5adce"   #----------------------------- Catppuccin Frappé Subtext0
warning-text="#e78284"   #----------------------- Catppuccin Frappé Red
text-special-one="#babbf1"   #------------------- Catppuccin Frappé Lavender
text-special-two="#a6d189"   #------------------- Catppuccin Frappé Green
top-bar-background="#a5adce"   #----------------- Catppuccin Frappé Subtext0
top-bar-text="#303446"   #----------------------- Catppuccin Frappé Base
status-bar-background="#a5adce"   #-------------- Catppuccin Frappé Subtext0
status-bar-text="#303446"   #-------------------- Catppuccin Frappé Base
status-bar-view-background="#babbf1"   #--------- Catppuccin Frappé Lavender
status-bar-view-text="#303446"   #--------------- Catppuccin Frappé Base
command-text="#c6d0f5"   #----------------------- Catppuccin Frappé Text
list-selected-background="#babbf1"   #----------- Catppuccin Frappé Lavender
list-selected-text="#303446"   #----------------- Catppuccin Frappé Base
list-selected-inactive-background="#51576d"   #-- Catppuccin Frappé Surface1
list-selected-inactive-text="#a5adce"   #-------- Catppuccin Frappé Subtext0
controls-text="#c6d0f5"   #---------------------- Catppuccin Frappé Text
controls-highlight="#a6d189"   #----------------- Catppuccin Frappé Green
autocomplete-background="#303446"   #------------ Catppuccin Frappé Base
autocomplete-text="#c6d0f5"   #------------------ Catppuccin Frappé Text
autocomplete-selected-background="#babbf1"   #--- Catppuccin Frappé Lavender
autocomplete-selected-text="#303446"   #--------- Catppuccin Frappé Base
button-color-one="#e78284"   #------------------- Catppuccin Frappé Red
button-color-two="#303446"   #------------------- Catppuccin Frappé Base
timeline-name-background="#303446"   #----------- Catppuccin Frappé Base
timeline-name-text="#babbf1"   #----------------- Catppuccin Frappé Lavender
